spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/db_invoice
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: create
    open-in-view: true
  kafka:
    consumer:
      bootstrap-servers:
        - ${KAFKA_URL:localhost:9092}
      group-id: group_invoice
      enable-auto-commit: 'true'
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.hibernate.sql: debug
