spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost:3306}/db_operation?serverTimezone=America/Bogota&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create
    open-in-view: true
  kafka:
    producer:
      bootstrap-servers:
        - ${KAFKA_URL:localhost:9092}
      retries: 0
      linger:
        ms: '0'
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org:
      hibernate:
        sql: debug
